services:
  postgres:
    image: postgres:16-alpine
    container_name: et_postgres
    restart: always
    environment:
      POSTGRES_USER: expensetracker
      POSTGRES_PASSWORD: expensetracker
      POSTGRES_DB: expensetracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expensetracker"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
